'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { apiClient } from '@/lib/api';
import { ReportData } from '@/lib/types';
import { formatDate } from '@/lib/format';

export default function ReportPage() {
  const params = useParams();
  const reportId = params.id as string;

  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const result = await apiClient.getReport(reportId);
        setReport(result);
        setLoading(false);
      } catch (err) {
        setError(`Failed to load report: ${String(err)}`);
        setLoading(false);
      }
    };

    fetchReport();
  }, [reportId]);

  const handleDownloadPDF = () => {
    if (!report) return;
    const element = document.getElementById('report-content');
    if (!element) return;

    const style = document.createElement('style');
    style.innerHTML = `
      @media print {
        body { background: white; color: black; }
        .no-print { display: none; }
      }
    `;
    document.head.appendChild(style);
    window.print();
  };

  if (loading) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="animate-pulse space-y-4">
          <div className="h-32 bg-ink-800 rounded-apple" />
          <div className="h-96 bg-ink-800 rounded-apple" />
        </div>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-12">
        <Link href="/" className="text-apple-blueBright hover:text-emerald-300 text-sm mb-8 inline-block">
          ← Back to Home
        </Link>
        <div className="bg-rose-500/10 border border-rose-500/30 rounded-apple-md p-8 text-rose-300 text-center">
          <p className="font-semibold mb-2">Failed to Load Report</p>
          <p className="text-sm">{error || 'Report not found'}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-4xl mx-auto px-4 py-12">
      <div className="flex items-center justify-between mb-8">
        <Link href="/" className="text-apple-blueBright hover:text-emerald-300 text-sm">
          ← Back to Home
        </Link>
        <button
          onClick={handleDownloadPDF}
          className="no-print px-4 py-2 bg-apple-blue hover:bg-apple-blueDark text-white font-semibold rounded-apple transition-colors text-sm"
        >
          Print / Export PDF
        </button>
      </div>

      <div
        id="report-content"
        className="bg-white text-slate-900 rounded-apple-md p-8 shadow-lg"
      >
        {/* Header */}
        <div className="border-b-2 border-slate-300 pb-6 mb-6">
          <h1 className="text-4xl font-bold text-slate-900 mb-2">{report.title}</h1>
          <p className="text-slate-600">
            Generated: {formatDate(report.created_at)}
          </p>
        </div>

        {/* Summary */}
        <div className="bg-slate-50 border border-slate-300 rounded-apple-md p-6 mb-8">
          <h2 className="text-xl font-bold text-slate-900 mb-3">Summary</h2>
          <p className="text-slate-700 leading-relaxed">{report.summary}</p>
        </div>

        {/* Main Content */}
        <div className="prose prose-sm max-w-none mb-8">
          <div className="text-slate-800 leading-relaxed whitespace-pre-wrap">
            {report.content}
          </div>
        </div>

        {/* Footer */}
        <div className="border-t border-slate-300 pt-6 text-xs text-slate-600">
          <p>
            This report was auto-generated by ChainTrace, a free open-source forensics tool.
            Analysis is based on on-chain data only. Conclusions are probabilistic and not
            confirmatory.
          </p>
          <p className="mt-2">
            For law enforcement use, supplementary investigation is required. See limitations
            policy.
          </p>
        </div>
      </div>

      {/* Meta Info */}
      <div className="mt-8 text-xs text-ink-400 text-center">
        <p>Report ID: {reportId}</p>
        {report.trace_id && <p>Trace ID: {report.trace_id}</p>}
        {report.address && <p>Address: {report.address}</p>}
      </div>
    </div>
  );
}
